#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AquaDroid.Resource", IsApplication=true)]

namespace AquaDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int hours_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int minutes_array = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int test = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int table_cell_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int table_row_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int table_row_last_bg = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int button1 = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int etprz2 = 2131165195;
			
			// aapt resource value: 0x7f070012
			public const int etprz3 = 2131165202;
			
			// aapt resource value: 0x7f070001
			public const int listView1 = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int sprwlh2 = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int sprwlh3 = 2131165198;
			
			// aapt resource value: 0x7f070015
			public const int sprwlh4 = 2131165205;
			
			// aapt resource value: 0x7f07001b
			public const int sprwlh5 = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int sprwlh6 = 2131165217;
			
			// aapt resource value: 0x7f070027
			public const int sprwlh7 = 2131165223;
			
			// aapt resource value: 0x7f07002d
			public const int sprwlh8 = 2131165229;
			
			// aapt resource value: 0x7f070008
			public const int sprwlm2 = 2131165192;
			
			// aapt resource value: 0x7f07000f
			public const int sprwlm3 = 2131165199;
			
			// aapt resource value: 0x7f070016
			public const int sprwlm4 = 2131165206;
			
			// aapt resource value: 0x7f07001c
			public const int sprwlm5 = 2131165212;
			
			// aapt resource value: 0x7f070022
			public const int sprwlm6 = 2131165218;
			
			// aapt resource value: 0x7f070028
			public const int sprwlm7 = 2131165224;
			
			// aapt resource value: 0x7f07002e
			public const int sprwlm8 = 2131165230;
			
			// aapt resource value: 0x7f070009
			public const int sprwylh2 = 2131165193;
			
			// aapt resource value: 0x7f070010
			public const int sprwylh3 = 2131165200;
			
			// aapt resource value: 0x7f070017
			public const int sprwylh4 = 2131165207;
			
			// aapt resource value: 0x7f07001d
			public const int sprwylh5 = 2131165213;
			
			// aapt resource value: 0x7f070023
			public const int sprwylh6 = 2131165219;
			
			// aapt resource value: 0x7f070029
			public const int sprwylh7 = 2131165225;
			
			// aapt resource value: 0x7f07002f
			public const int sprwylh8 = 2131165231;
			
			// aapt resource value: 0x7f07000a
			public const int sprwylm2 = 2131165194;
			
			// aapt resource value: 0x7f070011
			public const int sprwylm3 = 2131165201;
			
			// aapt resource value: 0x7f070018
			public const int sprwylm4 = 2131165208;
			
			// aapt resource value: 0x7f07001e
			public const int sprwylm5 = 2131165214;
			
			// aapt resource value: 0x7f070024
			public const int sprwylm6 = 2131165220;
			
			// aapt resource value: 0x7f07002a
			public const int sprwylm7 = 2131165226;
			
			// aapt resource value: 0x7f070030
			public const int sprwylm8 = 2131165232;
			
			// aapt resource value: 0x7f070005
			public const int stan1 = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int stan2 = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int stan3 = 2131165203;
			
			// aapt resource value: 0x7f070019
			public const int stan4 = 2131165209;
			
			// aapt resource value: 0x7f07001f
			public const int stan5 = 2131165215;
			
			// aapt resource value: 0x7f070025
			public const int stan6 = 2131165221;
			
			// aapt resource value: 0x7f07002b
			public const int stan7 = 2131165227;
			
			// aapt resource value: 0x7f070031
			public const int stan8 = 2131165233;
			
			// aapt resource value: 0x7f070002
			public const int ster1 = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int ster2 = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int ster3 = 2131165197;
			
			// aapt resource value: 0x7f070014
			public const int ster4 = 2131165204;
			
			// aapt resource value: 0x7f07001a
			public const int ster5 = 2131165210;
			
			// aapt resource value: 0x7f070020
			public const int ster6 = 2131165216;
			
			// aapt resource value: 0x7f070026
			public const int ster7 = 2131165222;
			
			// aapt resource value: 0x7f07002c
			public const int ster8 = 2131165228;
			
			// aapt resource value: 0x7f070003
			public const int wlgrzalka = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int wylgrzalka = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Relay = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
